### ISSUE TITLE
Can't mint because of transferOwnership was called

### ISSUE THREAD

**Issue by frdx** [ProjectOpenSea/opensea-creatures#132]
Hello, I've deployed my contract but it looks like I have the same issue as below where I can't mint because the transferOwnership was called to an address I don't own?

The transaction is here
https://rinkeby.etherscan.io/tx/0x6a7186aa78fa6e5f993606a397bc0305e78310ad1c4c34c0ee7d9017d911c605

@steffano , I believe the error's occurring for you due to the mintTo function only being available to the owner. 0x16811935c8b4deda61c2a9dd20db8ed7253729d5 which called the mintTo function created the contract, but ownership was transferred to 0x62a59189B8AF2aD4fDBDdC3d5164903112E298Cd  in the following transaction prior to the minTo function being called (about 6 blocks before): https://rinkeby.etherscan.io/tx/0x1b7a01ec7823aee358aa33e318fd71a88ddc6ad257f42b367e939bd0e6b334d9

Do you own the 0x62a59189B8AF2aD4fDBDdC3d5164903112E298Cd address / did you call transferOwnership?

_Originally posted by @TheMaxKim in https://github.com/ProjectOpenSea/opensea-creatures/issues/50#issuecomment-793550540_

**Comment by frdx** [comment]
So I think I am correct in using the below address but the txn is still failing on me, really can't figure out why

$env:OWNER_ADDRESS="0xC168D62eBA1EB8ad67495A24d1A2E814C0325416"
$env:FACTORY_CONTRACT_ADDRESS="0x54E063030aAfd9E3B53B1f99f1Bd9b97BC5F4b65"
$env:NETWORK="rinkeby"
node scripts/mint.js

The full error log is below:
(node:38888) UnhandledPromiseRejectionWarning: Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0x1845a8e51276b6df67c05a6339296546eb408cf9e734bb28e7d89078c1ce6b22",
  "blockNumber": 9330062,
  "contractAddress": null,
  "cumulativeGasUsed": 5823591,
  "effectiveGasPrice": "0x3b9aca09",
  "from": "0xc168d62eba1eb8ad67495a24d1a2e814c0325416",
  "gasUsed": 21928,
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0x54e063030aafd9e3b53b1f99f1bd9b97bc5f4b65",
  "transactionHash": "0x509169c0311294ff1ea0f817d1db6ddb79d11dd80a3a11f421240ac75201f5ab",
  "transactionIndex": 41,
  "type": "0x0",
  "events": {}
}
    at Object.TransactionError (D:\eth\delay_systems\node_modules\web3-core-helpers\lib\errors.js:87:21)
    at Object.TransactionRevertedWithoutReasonError (D:\eth\delay_systems\node_modules\web3-core-helpers\lib\errors.js:98:21)
    at D:\eth\delay_systems\node_modules\web3-eth\node_modules\web3-core-method\lib\index.js:393:57
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:38888) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 15)
(node:38888) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
