### ISSUE TITLE
scripts/mint.js returns UnhandledPromiseRejectionWarning: Error: Transaction has been reverted by the EVM:

### ISSUE THREAD

**Issue by soaphee** [ProjectOpenSea/opensea-creatures#50]
```at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:79963) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
(node:79963) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by soaphee** [comment]
in the deployed contract in the example, I am also seeing similar errors at https://rinkeby.etherscan.io/address/0xeba05c5521a3b81e23d15ae9b2d07524bc453561, https://rinkeby.etherscan.io/tx/0xa489673d6569126073a671ef245d22407495659d24e15ba32a5e557485837b3d

**Comment by steffano** [comment]
believe i'm encountering the same issue: https://rinkeby.etherscan.io/tx/0x1c1c5fd5348b185ffa20cfa5c771691cc953695db9e9fa00233e2bc7fe44b195

`~/Development/opensea-creatures(master):0 node scripts/mint.js
(node:1195) UnhandledPromiseRejectionWarning: Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0x555d97957fe658cde5dbf371dd148ce68a4785a7a74a49a4d310f533264483cd",
  "blockNumber": 8153105,
  "contractAddress": null,
  "cumulativeGasUsed": 1099820,
  "from": "0x16811935c8b4deda61c2a9dd20db8ed7253729d5",
  "gasUsed": 22762,
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0x34074a537cbac3a05312f6f14ef4c5d21babd826",
  "transactionHash": "0x1c1c5fd5348b185ffa20cfa5c771691cc953695db9e9fa00233e2bc7fe44b195",
  "transactionIndex": 9,
  "events": {}
}
    at Object.TransactionError (/Users/steffano/Development/opensea-creatures/node_modules/web3-eth/node_modules/web3-core-helpers/lib/errors.js:87:21)
    at Object.TransactionRevertedWithoutReasonError (/Users/steffano/Development/opensea-creatures/node_modules/web3-eth/node_modules/web3-core-helpers/lib/errors.js:98:21)
    at /Users/steffano/Development/opensea-creatures/node_modules/web3-eth/node_modules/web3-core-method/lib/index.js:394:57
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:1195) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 15)
(node:1195) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by ahmedelgammal** [comment]
any solution to this problem ?

**Comment by TheMaxKim** [comment]
Hey guys, I was just able to pull the repo and deploy / mint with the code.

@steffano , I believe the error's occurring for you due to the mintTo function only being available to the owner. 0x16811935c8b4deda61c2a9dd20db8ed7253729d5 which called the mintTo function created the contract, but ownership was transferred to 0x62a59189B8AF2aD4fDBDdC3d5164903112E298Cd  in the following transaction prior to the minTo function being called (about 6 blocks before): https://rinkeby.etherscan.io/tx/0x1b7a01ec7823aee358aa33e318fd71a88ddc6ad257f42b367e939bd0e6b334d9

Do you own the 0x62a59189B8AF2aD4fDBDdC3d5164903112E298Cd address / did you call transferOwnership?

@soaphee, the deployed contract (0x062D6D315e6C8AA196b9072d749E3f3F3579fDD0) that you reference is a sample that only the owner, currently 0xeba05c5521a3b81e23d15ae9b2d07524bc453561 which hasn't been changed since contract creation, is allowed to mint to. So calling mintTo from 0xe2bc300cc84b14f2c8eaba43021089c38841f02e as in the transaction https://rinkeby.etherscan.io/tx/0xa489673d6569126073a671ef245d22407495659d24e15ba32a5e557485837b3d would fail the onlyOwner check. I believe this repository is intended to be used to deploy your own version (which could be modified) of the contracts provided, which can then be minted and ownership controlled through the address that you deploy with.

**Comment by williamhuang0623** [comment]
Hey @TheMaxKim, what were the steps you took to deploy the repo? I am having a similar issue.

Error Message:
`
(node:91933) UnhandledPromiseRejectionWarning: Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0x10d4cf28d84b4083783585cb84b9ca27f3f142344784f54fcf85148110e98af7",
  "blockNumber": 8204232,
  "contractAddress": null,
  "cumulativeGasUsed": 434844,
  "from": "0xfab92e973096623f071f27eeaad5e7b647672cfd",
  "gasUsed": 22762,
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": false,
  "to": "0xad0381ec0fdc62ea0fc3465ca65fb465ad7295c0",
  "transactionHash": "0xbeab2f77a323c12aa40f148b8bc6e8113f9432b4cfd731fcad6ee29ab5b72772",
  "transactionIndex": 6,
  "events": {}
}
`

On [Rinkeby](https://rinkeby.etherscan.io/address/0xAd0381EC0Fdc62Ea0fc3465cA65fb465AD7295C0) it shows that the contract creator address 0xFaB92e973096623F071f27eEAAD5e7B647672cfd matches the `from` field in the error message above. I thought that meant that I am calling mintTo as the owner? Thanks for answering on this thread, been debugging this for awhile with no success. Any help is greatly appreciated.

**Comment by ahmedelgammal** [comment]
@TheMaxKim  I have the same problem. I ran the mint.js script just after the smart contract was deployed successfully. with the same owner MNEMONIC and OWNER_ADDRESS env variable setting. Contract address in my case is 0x106F2b480DAE74A7660C96F2E718A478DA315298

**Comment by TheMaxKim** [comment]
Hey @williamhuang0623 , @ahmedelgammal , @steffano , just realized that this is due to the commands in the instructions leading to a state where a factory contract is deployed which takes ownership over the NFT contract (missed some copy and paste in my repro since I used an env file).

This makes it so attempting to mint with the default instructions fails as the factory contract is the owner. I've created a PR to clarify the instructions, as well as prioritize attempting to mint through the factory contract if the address is specified as an env variable.

https://github.com/ProjectOpenSea/opensea-creatures/pull/54

Sorry for the issue, and thanks for the help in getting this issue known!

**Comment by ahmedelgammal** [comment]
@TheMaxKim  so can you clarify, how can we undo or roll back from this problem. Should we just deploy the contract now with the updated code ? how that interact with already existing contract ? I imagine it will be a new contract with a new address and the old one can be ignored ?

**Comment by williamhuang0623** [comment]
@TheMaxKim it's working on my end, thanks a ton for the quick turnaround!

**Comment by lyenliang** [comment]
Does anyone know the difference between `<deployed_contract_address>` and `<deployed_factory_contract_address>` in [README.md](https://github.com/ProjectOpenSea/opensea-creatures)?

**Comment by chahakshah111** [comment]
hey, i'm getting the same error for scripts/creature-accessories/advanced/mint.js
how can i solve that error @TheMaxKim can you please help me out. 
this is my deployed CreatureAccessoryLootBox: 0xe38990273d24Cd832150dc8647287d48dF5bd7E1

**Comment by adriadrop** [comment]
> hey, i'm getting the same error for scripts/creature-accessories/advanced/mint.js
> how can i solve that error @TheMaxKim can you please help me out.
> this is my deployed CreatureAccessoryLootBox: 0xe38990273d24Cd832150dc8647287d48dF5bd7E1

I have the same error for regular mint.js

**Comment by TheMaxKim** [comment]
These sound like these may be separate issues from what this issue was originally created for.

Could each of you create a new issue with more details including contract addresses or failed transaction hashes?

For @chahakshah111 , this looks like it might be due to not having minted any creature accessory lootboxes.

**Comment by cryptodogofmax** [comment]
Run command `yarn truffle deploy --network rinkeby --reset` instead of `yarn truffle deploy --network rinkeby`, then it works. I fixed the problem by adding --reset tag in the command.
