### ISSUE TITLE
Error: Invalid JSON RPC response

### ISSUE THREAD

**Issue by mamscience** [ProjectOpenSea/opensea-creatures#56]
Hello

Thanks for your all your efforts. I stumbled across the following error when deploying the contract.
The dry run runs fine, this error pop-ups in in the second run during the deployment. 
Anybody that has encountered this before and/or has a solution to this?

The error it throws is too large to copy, but basically happens right about here

```

Deploying 'Creature'
   --------------------
   > transaction hash:    0x8382b0697a64f6fd6880b49df255eb221f8222523d88ccd85b91d9d9f2b5e312
   ⠧ Blocks: 0            Seconds: 0Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/Users/m/opensea/opensea-creatures/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/web3/node_modules/web3-core-helpers/src/errors.js:42:1)
    at e.InvalidResponse [as onreadystatechange] (/Users/m/opensea/opensea-creatures/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/web3/node_modules/web3-providers-http/src/index.js:92:1)
    at e._a [as dispatchEvent] (/Users/m/opensea/opensea-creatures/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:27:61)
    at e.dispatchEvent [as _setReadyState] (/Users/m/opensea/opensea-creatures/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)
    at e._setReadyState [as _onHttpRequestError] (/Users/m/opensea/opensea-creatures/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request.js:349:1)
    at ClientRequest._onHttpRequestError (/Users/m/opensea/opensea-creatures/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request.js:252:47)

```

Manage too catch the following errors:

```
abort(Error: Invalid JSON RPC response: ""). Build with -s ASSERTIONS=1 for more info.
(Use `node --trace-uncaught ...` to show where the exception was thrown)
```

```
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module '/Users/m/opensea/opensea-creatures/...'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Thrown at:
    at Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Module._load (internal/modules/cjs/loader.js:841:27)
    at executeUserEntryPoint (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

```

Thanks in advance

**Comment by maisonam** [comment]
I'm having a similar issue, but get a slightly different output string:

Error: Invalid JSON RPC response: "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body>\r\n<center><h1>502 Bad Gateway</h1></center>\r\n</body>\r\n</html>\r\n"

not sure how to debug, any suggestions?

**Comment by tombenj** [comment]
@maisonam were you able to get around it somehow?

**Comment by TurgutB455** [comment]
I'm having a similar issue, any solutions?
