### ISSUE TITLE
sender doesn't have enough funds to send tx.

### ISSUE THREAD

**Issue by lyenliang** [ProjectOpenSea/opensea-creatures#66]
I ran into the following error when running `DEPLOY_CREATURES_SALE=1 yarn truffle deploy --network rinkeby`.

```
Error:  *** Deployment Failed ***

"Migrations" could not deploy due to insufficient funds
   * Account:  0xdbdaEc9734a614285DBAb3BEd8D1a97ba7xxxxxx
   * Balance:  0 wei
   * Message:  sender doesn't have enough funds to send tx. The upfront cost is: 10000000000000000 and the sender's account only has: 0
   * Try:
      + Using an adequately funded account
      + If you are using a local Geth node, verify that your node is synced.

    at /home/ec2-user/opensea-creatures/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:365:1
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Migration._deploy (/home/ec2-user/opensea-creatures/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:74:1)
    at Migration._load (/home/ec2-user/opensea-creatures/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:61:1)
    at Migration.run (/home/ec2-user/opensea-creatures/node_modules/truffle/build/webpack:/packages/migrate/Migration.js:212:1)
    at Object.runMigrations (/home/ec2-user/opensea-creatures/node_modules/truffle/build/webpack:/packages/migrate/index.js:150:1)
    at Object.runFrom (/home/ec2-user/opensea-creatures/node_modules/truffle/build/webpack:/packages/migrate/index.js:110:1)
    at Object.run (/home/ec2-user/opensea-creatures/node_modules/truffle/build/webpack:/packages/migrate/index.js:87:1)
    at runMigrations (/home/ec2-user/opensea-creatures/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:263:1)
    at setupDryRunEnvironmentThenRunMigrations (/home/ec2-user/opensea-creatures/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:251:1)
    at Object.run (/home/ec2-user/opensea-creatures/node_modules/truffle/build/webpack:/packages/core/lib/commands/migrate.js:220:1)
    at Command.run (/home/ec2-user/opensea-creatures/node_modules/truffle/build/webpack:/packages/core/lib/command.js:136:1)
Truffle v5.2.5 (core: 5.2.5)
Node v12.21.0
error Command failed with exit code 1.
```

Anyone knows why this happen?

Does the error mean that it needs to send some ethereum coins from my wallet?

**Comment by lyenliang** [comment]
This problem can be solved by [Rinkeby Ether faucet](https://faucet.rinkeby.io/).

```
Note that in order to deploy with Truffle and Infura, you'll need a "seed phrase" from a MetaMask account that is funded with Ether. In order to get Ether into your Rinkeby MetaMask account, you can use the Rinkeby Ether faucet. You'll need to post a message to one of your social profiles and paste the link to your post in the test faucet. In order to obtain your "seed phrase" from Metamask click "settings" and click "reveal seed words". Make sure you don't share your seed phrase for any accounts containing Mainnet tokens!
```
