### ISSUE TITLE
Invalid JSON RPC response: " "

### ISSUE THREAD

**Issue by johnnyshankman** [ProjectOpenSea/opensea-creatures#91]
Following readme. Able to connect to the test network etc and then suddenly can't deploy the contracts themselves.

I've triple checked that all of my `export`s are correctly set and that my wallet on the rinkeby network has funds.

```
± |master ✓| → DEPLOY_CREATURES_SALE=1 yarn truffle deploy --network rinkeby
yarn run v1.22.10
$ /Users/johnlshankman/Documents/workspace/opensea-creatures/node_modules/.bin/truffle deploy --network rinkeby

Compiling your contracts...
===========================
✔ Fetching solc version list from solc-bin. Attempt #1
> Everything is up to date, there is nothing to compile.



Migrations dry-run (simulation)
===============================
> Network name:    'rinkeby-fork'
> Network id:      4
> Block gas limit: 10000000 (0x989680)


1_initial_migrations.js
=======================
Error: Invalid JSON RPC response: ""
    at Object.InvalidResponse (/Users/johnlshankman/Documents/workspace/opensea-creatures/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/web3/node_modules/web3-core-helpers/src/errors.js:42:1)
    at t.InvalidResponse [as onreadystatechange] (/Users/johnlshankman/Documents/workspace/opensea-creatures/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/web3/node_modules/web3-providers-http/src/index.js:92:1)
    at t._a [as dispatchEvent] (/Users/johnlshankman/Documents/workspace/opensea-creatures/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:27:61)
    at t.dispatchEvent [as _setReadyState] (/Users/johnlshankman/Documents/workspace/opensea-creatures/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)
    at t._setReadyState [as _onHttpRequestError] (/Users/johnlshankman/Documents/workspace/opensea-creatures/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request.js:349:1)
    at ClientRequest._onHttpRequestError (/Users/johnlshankman/Documents/workspace/opensea-creatures/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/xhr2-cookies/dist/xml-http-request.js:252:47)
    at ClientRequest.emit (events.js:314:20)
    at TLSSocket.socketErrorListener (_http_client.js:427:9)
    at TLSSocket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by M1T10** [comment]
Exactly same error

**Comment by M1T10** [comment]
I'm not sure about it, but my mistake was to use a wrong node versione (I did yarn install --ignore-engines in order to ignore the versione required).
I started from scratch with the correct node version (used nvm to install version 12.18.4) and the mint worked flawlessly

**Comment by Kehrenkamp** [comment]
I also have a similar problem can someone please help me?

`Summary
=======
> Total deployments:   3
> Final cost:          0.02640197 ETH





Starting migrations...
======================
> Network name:    'live'
> Network id:      1
> Block gas limit: 30058619 (0x1caa87b)


1_initial_migrations.js
=======================

   Deploying 'Migrations'
   ----------------------
   > transaction hash:    0x4ff20df46929457ca56d9af774eee52fe19605a6688bd8c18adcc541be602c0f
   ⠏ Blocks: 52           Seconds: 629Error: Invalid JSON RPC response: "<html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body>\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n</body>\r\n</html>\r\n"
    at Object.InvalidResponse (/Users/Kehrenkamp/Desktop/opensea-creatures-master/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/web3/node_modules/web3-core-helpers/src/errors.js:42:1)
    at t.InvalidResponse [as onreadystatechange] (/Users/Kehrenkamp/Desktop/opensea-creatures-master/node_modules/truffle-hdwallet-provider/dist/webpack:/truffle-hdwallet-provider/Users/gnidan/src/work/truffle/node_modules/web3/node_modules/web3-providers-http/src/index.js:92:1)`

**Comment by vzherebetskyi** [comment]
@johnnyshankman 
it is mentioned in docs that
_This is often due to the truffle-hdwallet provider not being able to connect. Go to your Alchemy Dashboard (or infura.io) and create a new project. Use your "project ID" as your new ALCHEMY_KEY and make sure you export that command-line variable above._
